export {
	ClockCircleOutlined,
	CustomerServiceOutlined,
	DeleteOutlined,
	EyeInvisibleOutlined,
	EyeOutlined,
	FilePdfOutlined,
	MailFilled,
	LockOutlined,
	MailOutlined,
	MessageOutlined,
	PhoneOutlined,
	SendOutlined,
	UserOutlined,
} from '@ant-design/icons'
