export {
	ArrowLeftOutlined,
	MoreOutlined,
	PlusOutlined,
	CloseOutlined,
	ClockCircleOutlined,
	CustomerServiceOutlined,
	DeleteOutlined,
	EditOutlined,
	EyeInvisibleOutlined,
	EyeOutlined,
	FilePdfOutlined,
	MailFilled,
	LockOutlined,
	LeftOutlined,
	MailOutlined,
	MessageOutlined,
	PhoneOutlined,
	SendOutlined,
	UserOutlined,
	SaveOutlined,
	DownloadOutlined,
	CopyOutlined,
	SettingOutlined,
	UploadOutlined,
	CheckOutlined ,
} from '@ant-design/icons'
