export {
	ArrowLeftOutlined,
	MoreOutlined,
	PlusOutlined,
	CloseOutlined,
	ClockCircleOutlined,
	CustomerServiceOutlined,
	DeleteOutlined,
	EditOutlined,
	EyeInvisibleOutlined,
	EyeOutlined,
	FilePdfOutlined,
	MailFilled,
	LockOutlined,
	LeftOutlined,
	MailOutlined,
	MessageOutlined,
	PhoneOutlined,
	SendOutlined,
	UserOutlined,
	SaveOutlined,
	FileTextOutlined,
	ArrowRightOutlined,
	InboxOutlined,
	UploadOutlined,
	TableOutlined,
} from '@ant-design/icons'
